### ISSUE TITLE
Use the "flags" package

### ISSUE THREAD

**Issue by mstruebing** [mstruebing/tldr-go-client#5]
instead of manually parsing CLI arguments

**Comment by gavinwade12** [comment]
Would you be interested in using something like https://github.com/urfave/cli to make more of a command-like CLI (i.e. `git push`, `git pull`)? If not, I can use flags. I just feel this is more command oriented since not many of the flags actually require a value. Thoughts?

**Comment by mstruebing** [comment]
TBH I like the fact that I don't need 3rd party packages and would stick to this approach as long as possible. So if this isn't a problem for you I would rather use the `flags` package.
