### ISSUE TITLE
Let the tool act as a library

### ISSUE THREAD

**Issue by mstruebing** [mstruebing/tldr-go-client#6]
Feedback from @agnivade

> A common convention when you are writing a binary is to have the main.go inside a "cmd/tldr/main.go" folder and import what you need. That way your entire codebase acts as a library. https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1

**Comment by agnivade** [comment]
You can take a look at https://github.com/agnivade/funnel as an example.
